version: "3.9"

services:

    mongo:
        container_name: mongo
        image: mvertes/alpine-mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        expose:
            - 27017
        ports:
            - 27017:27017

    deno:
        build:
            dockerfile: Dockerfile
            context: .
        restart: always
        environment:
            - PORT=8000
            - MONGO_URI=mongodb://mongo:27017
            - DB=test
        expose:
            - 8000
        ports:
            - 8000:8000
        depends_on:
            - mongo
